project:
  type: website

website:
  title: "HOME"
  site-url: https://areberoto.github.io
  description: "Alberto's blog on AI/ML and embedded systems."
  navbar:
    left:
      - ai-ml.qmd
      - edge-ai.qmd
      - embedded-linux.qmd
    right:
      - ./certificates/certificates.qmd
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/areberoto
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



